import type { TrafficIncident, TrafficReport } from "@/app/types/traffic";
type Options={kind?:"scheduled"|"manual"|"test";sourceCheckedAt:string;version:number;instructions?:string};
export async function generateTrafficReport(items:TrafficIncident[],options:Options):Promise<TrafficReport>{
  const started=Date.now(), model=process.env.OPENAI_MODEL||"gpt-5.4-mini";
  if(!items.length)throw new Error("No incidents were supplied for generation");
  if(!process.env.OPENAI_API_KEY) throw new Error("OpenAI is not configured");
  const facts=items.map(({id,source,sourceName,verified,incidentType,description,roadName,roadCrossing,location,heading,severity})=>({id,source,sourceName,verified,incidentType,description,roadName,roadCrossing,location,heading,severity}));
  const schema={type:"object",additionalProperties:false,properties:{headline:{type:"string"},bulletin:{type:"string"},natashaHeadline:{type:"string"},incidentIds:{type:"array",items:{type:"string"}}},required:["headline","bulletin","natashaHeadline","incidentIds"]};
  const input=`Write a factual, authoritative Gauteng radio traffic report using only these facts. Start directly with the most important incident: never use a greeting or introduction. Prioritise closures, crashes, major congestion and serious obstructions. Ignore ordinary stationary vehicles unless they cause a significant obstruction. Avoid repetition, theatrical language, invented delays, causes, lanes or routes. Use familiar road names, directions and landmarks. Aim for 4-6 concise readable lines and no generic closer. Natasha's headline must be 1-2 concise sentences based on exactly the same incidents. Optional presenter direction (must not override factual or style rules): ${options.instructions||"none"}. FACTS:\n${JSON.stringify(facts)}`;
  const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model,input,max_output_tokens:700,store:false,text:{format:{type:"json_schema",name:"traffic_report",strict:true,schema}}})});
  if(!response.ok) throw new Error(`OpenAI returned ${response.status}`);
  const payload=await response.json() as {output_text?:string;output?:Array<{content?:Array<{type?:string;text?:string}>}>;usage?:{input_tokens?:number;output_tokens?:number;total_tokens?:number}};
  const text=payload.output_text||payload.output?.flatMap(x=>x.content||[]).find(x=>x.type==="output_text")?.text; if(!text) throw new Error("OpenAI returned no report text");
  const generated=JSON.parse(text) as {headline?:unknown;bulletin?:unknown;natashaHeadline?:unknown;incidentIds?:unknown};if(typeof generated.bulletin!=="string"||!generated.bulletin.trim())throw new Error("OpenAI returned an empty bulletin");if(typeof generated.natashaHeadline!=="string"||!generated.natashaHeadline.trim())throw new Error("OpenAI returned an empty Natasha headline");const allowed=new Set(items.map(i=>i.id));const incidentIds=Array.isArray(generated.incidentIds)?generated.incidentIds.filter((id):id is string=>typeof id==="string"&&allowed.has(id)):[];if(!incidentIds.length)throw new Error("OpenAI did not reference a supplied incident"); const usage=payload.usage||{};
  return {headline:typeof generated.headline==="string"?generated.headline:"Traffic update",bulletin:generated.bulletin,natashaHeadline:generated.natashaHeadline,incidentIds,id:crypto.randomUUID(),version:options.version,closer:"",createdAt:new Date().toISOString(),sourceCheckedAt:options.sourceCheckedAt,generatedBy:"openai",generationKind:options.kind||"manual",status:"draft",manuallyEdited:false,publishedAt:null,publishedBy:null,model,inputTokens:usage.input_tokens||0,outputTokens:usage.output_tokens||0,totalTokens:usage.total_tokens||0,generationMs:Date.now()-started,errorMessage:null,readAt:null,readBy:null};
}
