import{detectMeaningfulChanges,fetchTrafficSA,filterIncidentsByWindow,mergeSnapshotIncidents,selectRelevant}from"@/app/lib/traffic-source";
import{generateTrafficReport}from"@/app/lib/traffic-generate";
import{needsFreshScheduledDraft,shouldGenerateScheduled}from"@/app/lib/traffic-status";
import{addListener,clearPending,getLatestTrafficSnapshot,getWorkspace,markPending,recordCheckError,recordGenerationError,saveDraft,saveSnapshot,trafficDb}from"@/app/lib/traffic-store";
import type{ListenerInput}from"@/app/types/traffic";

export type GenerationOptions={minutes?:number;selectedIds?:string[];instructions?:string};
export const safeWorkflowError=(error:unknown)=>{const message=error instanceof Error?error.message:"Workflow failed";return message.replace(/Basic\s+[A-Za-z0-9+/=]+|Bearer\s+\S+|password=[^\s&]+/gi,"[redacted]").slice(0,500)};
export async function withWorkflowLock<T>(operation:()=>Promise<T>){const token=crypto.randomUUID(),db=trafficDb(),{data,error}=await db.rpc("acquire_traffic_workflow_lock",{p_token:token,p_seconds:180});if(error)throw error;if(!data)throw new Error("Another traffic workflow is already running");try{return await operation()}finally{const released=await db.rpc("release_traffic_workflow_lock",{p_token:token});if(released.error)console.error("Traffic workflow lock release failed")}}

async function checkUnlocked(){const previous=(await getLatestTrafficSnapshot())?.incidents||[];try{const fetched=await fetchTrafficSA(),seenAt=new Date().toISOString(),incidents=mergeSnapshotIncidents(previous,fetched,seenAt),changes=detectMeaningfulChanges(previous,incidents),snapshot=await saveSnapshot(incidents,changes.length);if(changes.length)await markPending(snapshot.id,changes.length);return{snapshot,changes}}catch(error){await recordCheckError(safeWorkflowError(error));throw error}}
export const checkTraffic=()=>withWorkflowLock(checkUnlocked);

async function generateUnlocked(kind:"scheduled"|"manual"|"test",options:GenerationOptions={}){const workspace=await getWorkspace();if(!workspace.snapshot)throw new Error("Check TrafficSA before generating");let eligible=filterIncidentsByWindow(workspace.snapshot.incidents,options.minutes??60);const manual=kind==="manual"&&Array.isArray(options.selectedIds);if(manual){const wanted=new Set(options.selectedIds),allowed=new Set(eligible.map(item=>item.id));eligible=eligible.filter(item=>wanted.has(item.id)&&allowed.has(item.id))}const selected=selectRelevant(eligible,Number.POSITIVE_INFINITY,manual);if(!selected.length)throw new Error("No eligible incidents are available for report generation");const db=trafficDb(),existing=await db.from("traffic_reports").select("id").eq("source_checked_at",workspace.snapshot.checkedAt).eq("generation_kind",kind).in("status",kind==="test"?["test"]:["draft","published"]).limit(1).maybeSingle();if(existing.error)throw existing.error;if(existing.data)throw new Error("A report already exists for this traffic state");try{const report=await generateTrafficReport(selected,{kind,sourceCheckedAt:workspace.snapshot.checkedAt,version:Date.now(),instructions:options.instructions});await saveDraft(report);await recordGenerationError(null);if(kind!=="test")await clearPending();return report}catch(error){await recordGenerationError(safeWorkflowError(error));throw error}}
export const generateLatest=(kind:"scheduled"|"manual"|"test",options:GenerationOptions={})=>withWorkflowLock(()=>generateUnlocked(kind,options));
export const testFullPipeline=(options:GenerationOptions={})=>withWorkflowLock(async()=>{const checked=await checkUnlocked();return{checked,report:await generateUnlocked("test",options)}});
export const addListenerSafely=(input:ListenerInput)=>withWorkflowLock(async()=>{const incident=await addListener(input);if(incident.verified)await markPending(null,1);return incident});
export const runScheduled=()=>withWorkflowLock(async()=>{const before=await getWorkspace(),checked=await checkUnlocked(),after=await getWorkspace(),legitimate=[before.draft,before.updatedDraft,before.published].filter(report=>report&&report.generationKind!=="test").sort((a,b)=>new Date(b!.createdAt).getTime()-new Date(a!.createdAt).getTime())[0],fresh=needsFreshScheduledDraft(legitimate?.createdAt||null);if(!shouldGenerateScheduled(after.pendingGeneration,legitimate?.createdAt||null))return{generated:false,changes:checked.changes.length};const report=await generateUnlocked("scheduled",{minutes:60});return{generated:true,changes:checked.changes.length,reportId:report.id,freshDayDraft:fresh,preservedManualEdit:Boolean((await getWorkspace()).draft?.manuallyEdited)}});
